// 뱅크(악기 묶음) 여러 개. PC는 스페이스바, 터치는 오른쪽 아래 칸으로 뱅크를 바꾼다.
// 뱅크마다 배경 그림과 영상 겹치는 방식(blend)을 정한다:
//   darken  = 밝은 종이 위 먹·색 (흰 바탕·종이색은 사라지고 그림만 남는다)
//   lighten = 어두운 배경 위 색 (검은 바탕은 사라지고 색만 남는다) — 검은 바탕 클립을 쓸 때
// 패드 한 줄 = 키 하나. sound는 빼도 된다 (영상만 나온다).
// flip: true 면 누를 때마다 영상을 좌우·상하로 무작위 반전한다 (직전과는 다른 방향으로).
// 영상은 1920x1080, 밝은 바탕(한지·흰색) 위 그림이고, 끝 프레임은 빈 바탕이어야 한다.
window.BANKS = [
  {
    name: "수묵",
    background: "assets/hanji.jpg",
    blend: "darken",
    pads: [
      { key: "a", name: "꽹과리 지 (강)",      sound: "sounds/kkwaenggwari_ji_strong.wav",   clip: "clips/sumuk/ji_a.mp4", flip: true },
      { key: "s", name: "꽹과리 게르르르 (강)", sound: "sounds/kkwaenggwari_roll_strong.wav", clip: "clips/sumuk/roll_s.mp4", flip: true },
      { key: "d", name: "징 (강)",             sound: "sounds/jing_strong.wav",              clip: "clips/sumuk/jing_d.mp4", flip: true },
      { key: "f", name: "징 (약)",             sound: "sounds/jing_soft.wav",                clip: "clips/sumuk/jing_f.mp4", flip: true },
      { key: "g", name: "장구 덩 (강)", sound: "sounds/janggu_deong_strong.wav", clip: "clips/sumuk/deong_g.mp4", flip: true },
      { key: "t", name: "장구 덩 (중)", sound: "sounds/janggu_deong_mid.wav", clip: "clips/sumuk/deong_t.mp4", flip: true },
      { key: "h", name: "장구 쿵 (강)", sound: "sounds/janggu_kung_strong.wav", clip: "clips/sumuk/kung_h.mp4", flip: true },
      { key: "y", name: "장구 쿵 (중)", sound: "sounds/janggu_kung_mid.wav", clip: "clips/sumuk/kung_y.mp4", flip: true },
      { key: "j", name: "장구 덕 (강)", sound: "sounds/janggu_deok_strong.wav", clip: "clips/sumuk/deok_j.mp4", flip: true },
      { key: "u", name: "장구 덕 (중)", sound: "sounds/janggu_deok_mid.wav", clip: "clips/sumuk/deok_u.mp4", flip: true },
      { key: "k", name: "장구 기덕 (강)", sound: "sounds/janggu_gideok_strong.wav", clip: "clips/sumuk/gideok_k.mp4", flip: true },
      { key: "i", name: "장구 기덕 (중)", sound: "sounds/janggu_gideok_mid.wav", clip: "clips/sumuk/gideok_i.mp4", flip: true },
      { key: "l", name: "장구 더 (강)", sound: "sounds/janggu_deo_strong.wav", clip: "clips/sumuk/deo_l.mp4", flip: true },
      { key: "o", name: "장구 더 (중)", sound: "sounds/janggu_deo_mid.wav", clip: "clips/sumuk/deo_o.mp4", flip: true },
      { key: "p", name: "장구 더러러러 (강)", sound: "sounds/janggu_deororeo_strong.wav", clip: "clips/sumuk/deororeo_p.mp4", flip: true },
      { key: "z", name: "추임새 얼쑤", sound: "sounds/chuimsae_eolssu.wav", clip: "clips/sumuk/eolssu_z.mp4", flip: true },
      { key: "x", name: "추임새 얼씨구", sound: "sounds/chuimsae_eolssigu.wav", clip: "clips/sumuk/eolssigu_x.mp4", flip: true },
      { key: "c", name: "추임새 좋다", sound: "sounds/chuimsae_jota.wav", clip: "clips/sumuk/jota_c.mp4", flip: true },
      { key: "q", name: "꽹과리 객 (강)", sound: "sounds/kkwaenggwari_gaek_strong.wav", clip: "clips/sumuk/gaek_q.mp4", flip: true },
      { key: "w", name: "꽹과리 갯 (강)", sound: "sounds/kkwaenggwari_gaet_strong.wav", clip: "clips/sumuk/gaet_w.mp4", flip: true },
      { key: "e", name: "북 노고 (중)", sound: "sounds/buk_nogo_mid.wav", clip: "clips/sumuk/nogo_e.mp4", flip: true },
      { key: "r", name: "북 절고 (중)", sound: "sounds/buk_jeolgo_mid.wav", clip: "clips/sumuk/jeolgo_r.mp4", flip: true },
      { key: "v", name: "북 노고 (강)", sound: "sounds/buk_nogo_strong.wav", clip: "clips/sumuk/nogo_v.mp4", flip: true },
      { key: "b", name: "북 절고 (강)", sound: "sounds/buk_jeolgo_strong.wav", clip: "clips/sumuk/jeolgo_b.mp4", flip: true },
      { key: "n", name: "추임새 쑤", sound: "sounds/chuimsae_ssu.wav", clip: "clips/sumuk/ssu_n.mp4", flip: true },
      { key: "m", name: "추임새 어이", sound: "sounds/chuimsae_eoi.wav", clip: "clips/sumuk/eoi_m.mp4", flip: true },
    ],
  },
  {
    name: "단청",
    background: "assets/hanji_aged.jpg",
    blend: "darken",
    pads: [
      { key: "a", name: "단소 8 · 연꽃", sound: "sounds/danso_8.wav", clip: "clips/dancheong/dc01_lotus_bloom.mp4", flip: true },
      { key: "s", name: "단소 6 · 물결", sound: "sounds/danso_6.wav", clip: "clips/dancheong/dc02_wave_sweep.mp4", flip: true },
      { key: "d", name: "대금 니나 5 · 기와 문양", sound: "sounds/daegeum_nina_05.wav", clip: "clips/dancheong/dc03_tile_medallions.mp4", flip: true },
      { key: "f", name: "대금 니나 6 · 머리초 띠", sound: "sounds/daegeum_nina_06.wav", clip: "clips/dancheong/dc04_meoricho_band.mp4", flip: true },
      { key: "q", name: "대금 니나 10 · 육각 살창", sound: "sounds/daegeum_nina_10.wav", clip: "clips/dancheong/dc05_hex_lattice.mp4", flip: true },
      { key: "w", name: "소금 노니로 · 구름 무늬", sound: "sounds/sogeum_noniro.wav", clip: "clips/dancheong/dc06_cloud_scroll.mp4", flip: true },
      { key: "e", name: "대금 니나 11 · 아자 살창", sound: "sounds/daegeum_nina_11.wav", clip: "clips/dancheong/dc07_aja_lattice.mp4", flip: true },
      { key: "r", name: "나각 · 보주 소용돌이", sound: "sounds/nagak.wav", clip: "clips/dancheong/dc08_jewel_spiral.mp4", flip: true },
      { key: "t", name: "소금 깊은농음 · 오색 물결무늬", sound: "sounds/sogeum_gipeun_nongeum.wav", clip: "clips/dancheong/dc09_rainbow_ripple.mp4", flip: true },
      { key: "y", name: "산조대금 · 쌍 연꽃", sound: "sounds/sanjo_daegeum.wav", clip: "clips/dancheong/dc10_twin_lotus.mp4", flip: true },
      { key: "u", name: "대금 니나 12 · 별꽃", sound: "sounds/daegeum_nina_12.wav", clip: "clips/dancheong/dc11_star_rosette.mp4", flip: true },
      { key: "i", name: "대금 니나 13 · 소란 격자", sound: "sounds/daegeum_nina_13.wav", clip: "clips/dancheong/dc12_soran_grid.mp4", flip: true },
      { key: "o", name: "대금 니나 14 · 기둥 띠", sound: "sounds/daegeum_nina_14.wav", clip: "clips/dancheong/dc13_pillar_bands.mp4", flip: true },
      { key: "p", name: "소금 노르니르 · 매화 흩날림", sound: "sounds/sogeum_noreunireu.wav", clip: "clips/dancheong/dc14_maehwa_scatter.mp4", flip: true },
      { key: "g", name: "피리 · 솟는 물결", sound: "sounds/piri_14.wav", clip: "clips/dancheong/dc15_wave_rise.mp4", flip: true },
      { key: "h", name: "대금 니나 7 · 아치 꽃줄", sound: "sounds/daegeum_nina_07.wav", clip: "clips/dancheong/dc16_arch_garland.mp4", flip: true },
      { key: "j", name: "대금 니나 8 · 꽃잎 바퀴", sound: "sounds/daegeum_nina_08.wav", clip: "clips/dancheong/dc17_clock_petals.mp4", flip: true },
      { key: "k", name: "대금 니나 9 · 팔각 물결", sound: "sounds/daegeum_nina_09.wav", clip: "clips/dancheong/dc18_octagon_ripple.mp4", flip: true },
      { key: "l", name: "단소 9 · 연꽃 고리", sound: "sounds/danso_9.wav", clip: "clips/dancheong/dc19_lotus_ring.mp4", flip: true },
      { key: "z", name: "대금 니나 1 · 마름모 사슬", sound: "sounds/daegeum_nina_01.wav", clip: "clips/dancheong/dc20_diamond_chain.mp4", flip: true },
      { key: "x", name: "대금 니나 2 · 뇌문 틀", sound: "sounds/daegeum_nina_02.wav", clip: "clips/dancheong/dc21_fret_frame.mp4", flip: true },
      { key: "c", name: "소금 나니루 · 떨어지는 꽃잎", sound: "sounds/sogeum_naniru.wav", clip: "clips/dancheong/dc22_falling_petals.mp4", flip: true },
      { key: "v", name: "나발 · 햇살", sound: "sounds/nabal.wav", clip: "clips/dancheong/dc23_sun_rays.mp4", flip: true },
      { key: "b", name: "단소 7 · 흐르는 구름", sound: "sounds/danso_7.wav", clip: "clips/dancheong/dc24_cloud_drift.mp4", flip: true },
      { key: "n", name: "대금 니나 3 · 육각 십자", sound: "sounds/daegeum_nina_03.wav", clip: "clips/dancheong/dc25_hexa_cross.mp4", flip: true },
      { key: "m", name: "대금 니나 4 · 모서리 부채", sound: "sounds/daegeum_nina_04.wav", clip: "clips/dancheong/dc26_corner_fans.mp4", flip: true },
    ],
  },
];
